port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50100
  use_external_ip: true
  # Masukkan IP publik server untuk production
  # external_ip: "1.2.3.4"

turn:
  enabled: false

room:
  max_participants: 500
  empty_timeout: 300
  departure_timeout: 20

logging:
  level: info
  json: true
