# Listener MQTT biasa (internal)
listener 1883
protocol mqtt

# Listener MQTT over TLS (aktifkan setelah SSL tersedia)
# listener 8883
# protocol mqtt
# cafile /etc/ssl/letsencrypt/live/DOMAIN/chain.pem
# certfile /etc/ssl/letsencrypt/live/DOMAIN/fullchain.pem
# keyfile /etc/ssl/letsencrypt/live/DOMAIN/privkey.pem
# tls_version tlsv1.2

# Listener MQTT over WebSocket
listener 9001
protocol websockets

# Auth
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl

# Persistence
persistence true
persistence_location /mosquitto/data/

# Logging
log_dest stdout
log_type all
